### ISSUE TITLE
Create a proof_of_concept.md example.

### ISSUE THREAD

**Issue by marceljar** [SenecaCollegeBTSProjects/Group_0#6]
This file should contain a description of the system components that the students are going to implement for iteration 1. In case they make any simplifications, such as hard-coding parts of the information that should have come from the database, it needs to be specified.

For our example, it should contemplate only the meeting-picking part.

**Comment by bczegel** [comment]
Resolved by https://github.com/SenecaCollegeBTSProjects/Group_0/commit/07374c8722b38f3ed8e96c8ba7a64e94bb1ca5c8#diff-7334475ea7301f37e2d0a539515cffe8
